### ISSUE TITLE
Non-disappearance of 'Zeros' in "Rating_Sum" column

### ISSUE THREAD

**Issue by Nithish1201** [Nithish1201/Success_prediction_of_app#1]
@mgvel sir.
I have an issue running the EDA.ipynb file completely..!!
If you take a complete look at the notebook, you can see that I have dropped(in place = True) all rows having "Rating_Sum" as 'zero'.
But if I try to plot that column, I still get the graph which is having zeros in it.
Could u pls check them and clear this issue, sir..!!

**Comment by mgvel** [comment]
I will take a look @Nithish1201

**Comment by mgvel** [comment]
## There were no zero rows in that data

```py
is_zero  = data['Rating_Sum']==0.0
print(is_zero.head())

zero_data = data[is_zero]
zero_data
```

## Min - Max also good. 
```py
min(data["Rating_Sum"])
```

```sh
5.0
```


```py
max(data["Rating_Sum"])
```

```sh
252114408.0
```

### But as you can see, x axis has extreme values. 

if you compare 5.0 against 250 million, that's going to look like zero. :)

**Comment by Nithish1201** [comment]
so basically it means, that outliers are to be detected and removed.
is it sir..??
