### ISSUE TITLE
What is "-inf" in numpy and pandas

### ISSUE THREAD

**Issue by Nithish1201** [Nithish1201/Success_prediction_of_app#3]
@mgvel sir..!!
I am getting many "-inf " values in a column that I reproduced(Average_Downloads) in the EDA.ipynb notebook(in the last cell).
Does that mean infinity ??
Can you clarify what is that and are they required or should I take them off??
How can I mitigate them?

**Comment by mgvel** [comment]
Make sure, you are `NOT` dividing something with `zero` that will cause `-inf`.

**Comment by Nithish1201** [comment]
oh ok, thank you, sir...got it
